---
exclude: |
  (?x)^(
    \.venv/|
    migrations/|
    __pycache__/|
    \.git/|
    \.env|
    tests/fixtures/|
    docs/_build/|
    \.github/
  )

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
      #   args: [--line-length=120]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev:  v1.15.0
  #   hooks:
  #     - id: mypy
  #       # args: [--ignore-missing-imports]
  #       additional_dependencies: [types-pytz]
