---
version: "3.8"

services:
  db:
    image: postgres:15.5
    container_name: weekender_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - weekender_net

  bot:
    build: .
    container_name: weekender_bot
    env_file:
      - .env
    volumes:
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    networks:
      - weekender_net

volumes:
  postgres_data:

networks:
  weekender_net:
    driver: bridge
