"""added events and interests

Revision ID: 18938657e3dc
Revises:
Create Date: 2025-05-19 20:52:37.144585

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '18938657e3dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'events_interests',
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('interest_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['interest_id'], ['options.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('event_id', 'interest_id'),
    )
    op.create_index(op.f('ix_events_interests_event_id'), 'events_interests', ['event_id'], unique=False)
    op.create_index(op.f('ix_events_interests_interest_id'), 'events_interests', ['interest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_interests_interest_id'), table_name='events_interests')
    op.drop_index(op.f('ix_events_interests_event_id'), table_name='events_interests')
    op.drop_table('events_interests')
    # ### end Alembic commands ###
