"""add user profession and about

Revision ID: 6b898737b754
Revises: 438cd264ce5a
Create Date: 2025-06-26 21:15:34.054020

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6b898737b754'
down_revision: Union[str, None] = '438cd264ce5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profession', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    op.drop_column('users', 'profession')
    # ### end Alembic commands ###
