"""adding a user column to the table total_like

Revision ID: 2d3c82f8c2e3
Revises: cf93afee5f43
Create Date: 2025-07-17 12:37:43.663986

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2d3c82f8c2e3'
down_revision: Union[str, None] = 'cf93afee5f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_likes', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_likes')
    # ### end Alembic commands ###
