"""add table like and friends

Revision ID: cf93afee5f43
Revises: 6b898737b754
Create Date: 2025-07-10 12:43:00.522204

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cf93afee5f43'
down_revision: Union[str, None] = '6b898737b754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'friend_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('from_user_id', sa.Integer(), nullable=False),
        sa.Column('to_user_id', sa.Integer(), nullable=False),
        sa.Column('date_create', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_reciprocated', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('from_user_id', 'to_user_id', name='unique_friend_request'),
    )
    op.create_index('ix_friend_request_date_create', 'friend_requests', ['date_create'], unique=False)
    op.create_index('ix_friend_request_reciprocated', 'friend_requests', ['is_reciprocated'], unique=False)
    op.create_index(op.f('ix_friend_requests_from_user_id'), 'friend_requests', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_to_user_id'), 'friend_requests', ['to_user_id'], unique=False)
    op.create_table(
        'like_profile',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('from_user_id', sa.Integer(), nullable=False),
        sa.Column('to_user_id', sa.Integer(), nullable=False),
        sa.Column('date_create', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_reciprocated', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('from_user_id', 'to_user_id', name='unique_like'),
    )
    op.create_index('ix_like_profile_date_create', 'like_profile', ['date_create'], unique=False)
    op.create_index(op.f('ix_like_profile_from_user_id'), 'like_profile', ['from_user_id'], unique=False)
    op.create_index('ix_like_profile_reciprocated', 'like_profile', ['is_reciprocated'], unique=False)
    op.create_index(op.f('ix_like_profile_to_user_id'), 'like_profile', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_like_profile_to_user_id'), table_name='like_profile')
    op.drop_index('ix_like_profile_reciprocated', table_name='like_profile')
    op.drop_index(op.f('ix_like_profile_from_user_id'), table_name='like_profile')
    op.drop_index('ix_like_profile_date_create', table_name='like_profile')
    op.drop_table('like_profile')
    op.drop_index(op.f('ix_friend_requests_to_user_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_from_user_id'), table_name='friend_requests')
    op.drop_index('ix_friend_request_reciprocated', table_name='friend_requests')
    op.drop_index('ix_friend_request_date_create', table_name='friend_requests')
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
