---
name: Deploy Bot

on:
  push:
    branches: [main]

if: "!contains(github.event.head_commit.message, '[skip ci]') || !contains(github.event.head_commit.message, '[no deploy]')"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Ruff linter
        run: ruff check .

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mypy
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install types-pytz
      - name: Run Mypy
        run: mypy --ignore-missing-imports --exclude migrations .

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, types]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Verify SSH connection
        run: |
          ssh -o BatchMode=yes \
              -p ${{ secrets.SSH_PORT }} \
              -i ~/.ssh/id_ed25519 \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'" || {
            echo "::error::SSH connection failed"
            echo "Debug info:"
            echo "1. Проверьте формат SSH_PRIVATE_KEY в Secrets"
            echo "2. Проверьте содержимое ~/.ssh/authorized_keys на сервере"
            echo "3. Проверьте логи на сервере: sudo tail -f /var/log/auth.log"
            exit 1
          }

      - name: Deploy application
        run: |
          ssh -T -p ${{ secrets.SSH_PORT }} \
              -i ~/.ssh/id_ed25519 \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -euo pipefail

          # Установка переменных окружения
          export BOT_TOKEN='${{ secrets.BOT_TOKEN }}'
          export POSTGRES_USER='${{ secrets.POSTGRES_USER }}'
          export POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}'
          export POSTGRES_DB='${{ secrets.POSTGRES_DB }}'
          export DATABASE_URL="postgresql+asyncpg://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB"

          echo "🚀 Начало процесса деплоя..."
          cd ~/weekender_bot || { echo "❌ Ошибка перехода в директорию проекта"; exit 1; }

          # Обновление кода
          echo "🔄 Обновление кода из репозитория..."
          git fetch --all
          git reset --hard origin/main

          # Обновление .env
          echo "⚙️ Обновление .env файла..."
          [ -f .env ] || touch .env
          grep -v -e "BOT_TOKEN=" -e "POSTGRES_.*=" -e "DATABASE_URL=" .env > .env.tmp || true
          mv .env.tmp .env

          echo "BOT_TOKEN=$BOT_TOKEN" >> .env
          echo "POSTGRES_DB=$POSTGRES_DB" >> .env
          echo "POSTGRES_USER=$POSTGRES_USER" >> .env
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
          echo "DATABASE_URL=$DATABASE_URL" >> .env

          # Проверка файлов миграций
          echo "🔍 Проверка файлов миграций..."
          if [ ! -f alembic.ini ] || [ ! -d migrations ]; then
            echo "❌ Отсутствуют необходимые файлы миграций!"
            exit 1
          fi

          # Пересборка и запуск
          echo "🔨 Пересборка и запуск только сервиса бота..."
          docker-compose build --no-cache bot
          docker-compose up -d --force-recreate bot

          # Проверка файлов в контейнере
          echo "🔎 Проверка файлов в контейнере бота..."
          docker-compose exec bot sh -c "\
            [ -f /app/alembic.ini ] || { echo '❌ alembic.ini не найден'; exit 1; } && \
            [ -d /app/migrations ] || { echo '❌ Папка migrations не найдена'; exit 1; } && \
            [ -f /app/migrations/env.py ] || { echo '❌ env.py не найден'; exit 1; }"

          # Применение миграций
          echo "🔄 Применение миграций..."
          docker-compose exec bot sh -c "
            cd /app && \
            if ! alembic current &>/dev/null; then \
              echo 'ℹ️ Таблица версий не найдена, инициализация...'; \
              alembic stamp head || { echo '❌ Ошибка инициализации'; exit 1; }; \
            fi && \
            echo 'ℹ️ Применение миграций...'; \
            alembic upgrade head || { echo '❌ Ошибка применения миграций'; exit 1; }" 2>&1 | tee alembic.log

          # Проверка результата
          echo "✅ Проверка результата миграций..."
          docker-compose exec db psql -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT * FROM alembic_version" || {
            echo "❌ Таблица версий не создана! Повторная попытка..."
            docker-compose exec bot alembic stamp head || {
              echo "❌❌ Критическая ошибка: не удалось создать таблицу версий";
              exit 1;
            }
          }

          # Финальная проверка
          echo "🔍 Проверка сервисов..."
          docker-compose ps
          docker-compose logs --tail=20

          echo "🎉 Деплой успешно завершен!"
          EOF
