---
name: Deploy Bot

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Ruff linter
        run: ruff check .

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mypy
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install types-pytz
      - name: Run Mypy
        run: mypy --ignore-missing-imports --exclude migrations .

  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') || !contains(github.event.head_commit.message, '[no deploy]')"
    needs: [lint, types]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Verify SSH connection
        run: |
          ssh -o BatchMode=yes \
              -p ${{ secrets.SSH_PORT }} \
              -i ~/.ssh/id_ed25519 \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'" || {
            echo "::error::SSH connection failed"
            echo "Debug info:"
            echo "1. Проверьте формат SSH_PRIVATE_KEY в Secrets"
            echo "2. Проверьте содержимое ~/.ssh/authorized_keys на сервере"
            echo "3. Проверьте логи на сервере: sudo tail -f /var/log/auth.log"
            exit 1
          }

      - name: Deploy application
        run: |
          ssh -T -p ${{ secrets.SSH_PORT }} \
              -i ~/.ssh/id_ed25519 \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -euo pipefail

          # Установка переменных окружения
          export BOT_TOKEN='${{ secrets.BOT_TOKEN }}'
          export POSTGRES_USER='${{ secrets.POSTGRES_USER }}'
          export POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}'
          export POSTGRES_DB='${{ secrets.POSTGRES_DB }}'
          export DATABASE_URL="postgresql+asyncpg://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB"

          echo "🚀 Начало процесса деплоя..."
          cd ~/weekender_bot || { echo "❌ Ошибка перехода в директорию проекта"; exit 1; }

          # Обновление кода
          echo "🔄 Обновление кода из репозитория..."
          git fetch --all
          git reset --hard origin/main

          # Проверка наличия файлов окружения
          echo "🔍 Проверка наличия файлов окружения..."
          if [ ! -f .env ]; then
            echo "❌ Файл .env не найден! Скопируйте его вручную на сервер."
            exit 1
          fi

          # Проверка файлов миграций (только их наличие)
          echo "🔍 Проверка наличия файлов миграций..."
          if [ ! -f alembic.ini ] || [ ! -d migrations ]; then
            echo "⚠️ Внимание: отсутствуют файлы миграций, но это может быть нормально для первого деплоя"
          fi

          # Пересборка и запуск
          echo "🔨 Пересборка и запуск только сервиса бота..."
          docker-compose build --no-cache bot
          docker-compose up -d --force-recreate bot

          # Надежная проверка существования таблицы alembic_version
          echo "🔍 Проверка существования таблицы alembic_version..."
          if ! docker-compose exec db sh -c 'PGPASSWORD=$POSTGRES_PASSWORD psql -h db -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT 1 FROM alembic_version LIMIT 1"' &>/dev/null; then
            echo "⚙️ Таблица версий не найдена, инициализируем..."
            docker-compose exec bot alembic stamp head || {
              echo "❌ Ошибка создания таблицы версий"
              exit 1
            }
          fi

          # Обновленная проверка необходимости миграций
          echo "🔍 Проверка необходимости применения миграций..."
          MIGRATION_NEEDED=$(docker-compose exec bot sh -c "cd /app && alembic current | grep -c '(head)'" | tr -d '[:space:]')

          if [ "$MIGRATION_NEEDED" -eq 0 ]; then
            echo "ℹ️ Неприменённые миграции обнаружены, начинаем процесс..."

            # Инициализация если нужно
            echo "🔄 Проверка состояния миграций..."
            if ! docker-compose exec bot sh -c "cd /app && alembic current &>/dev/null"; then
              echo "⚙️ Инициализация таблицы версий..."
              docker-compose exec bot sh -c "cd /app && alembic stamp head" || {
                echo "❌ Ошибка инициализации миграций"
                exit 1
              }
            fi

            # Применение миграций
            echo "🔄 Применение миграций..."
            docker-compose exec bot sh -c "cd /app && alembic upgrade head" || {
              echo "❌ Ошибка применения миграций"
              exit 1
            }
          else
            echo "✅ Все миграции уже применены, пропускаем этот шаг"
          fi

          # Финальная проверка
          echo "🔍 Проверка сервисов..."
          docker-compose ps
          docker-compose logs --tail=20 bot

          echo "🎉 Деплой успешно завершен!"
          EOF
